# Generated by Django 5.2.7 on 2025-11-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='nombre_producto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.producto'),
        ),
    ]
