# Generated by Django 5.2.7 on 2026-03-18 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_options_and_more'),
        ('tienda', '0002_categoria_alter_producto_options_producto_destacado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineapedido',
            options={'verbose_name': 'Línea de pedido', 'verbose_name_plural': 'Líneas de pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-id'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.producto'),
        ),
    ]
