# Generated by Django 5.2.7 on 2025-11-12 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('tipo_servicio', models.CharField(max_length=150)),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['titulo']},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='created',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='updated',
        ),
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio_desde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='slug',
            field=models.SlugField(default='', max_length=160, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='ReservaServicio',
        ),
    ]
